/* AUTO-GENERATED by tools/codegen.py — DO NOT EDIT.
 * Source: docs/sdk_enums.json */
#ifndef NFSMW_SDK_GENERATED_ENUMS_H
#define NFSMW_SDK_GENERATED_ENUMS_H

#include <stdint.h>

typedef enum NFSMW_ActionID {
    NFSMW_ActionID_NULL_ACTION = 0,
    NFSMW_ActionID_GAMEACTION_STEERLEFT = 1,
    NFSMW_ActionID_GAMEACTION_STEERRIGHT = 2,
    NFSMW_ActionID_GAMEACTION_TURNLEFT = 3,
    NFSMW_ActionID_GAMEACTION_TURNRIGHT = 4,
    NFSMW_ActionID_GAMEACTION_GAS = 5,
    NFSMW_ActionID_GAMEACTION_BRAKE = 6,
    NFSMW_ActionID_GAMEACTION_HANDBRAKE = 7,
    NFSMW_ActionID_GAMEACTION_GAMEBREAKER = 8,
    NFSMW_ActionID_GAMEACTION_SHIFTUP = 9,
    NFSMW_ActionID_GAMEACTION_SHIFTDOWN = 10,
    NFSMW_ActionID_GAMEACTION_NOS = 11,
    NFSMW_ActionID_GAMEACTION_RESET = 12,
    NFSMW_ActionID_GAMEACTION_FORWARD = 13,
    NFSMW_ActionID_GAMEACTION_BACK = 14,
    NFSMW_ActionID_GAMEACTION_JUMP = 15,
    NFSMW_ActionID_GAMEACTION_DEBUGHUMAN1 = 16,
    NFSMW_ActionID_GAMEACTION_DEBUGHUMAN2 = 17,
    NFSMW_ActionID_GAMEACTION_DEBUGHUMAN3 = 18,
    NFSMW_ActionID_GAMEACTION_DEBUGHUMAN4 = 19,
    NFSMW_ActionID_CAMERAACTION_CHANGE = 20,
    NFSMW_ActionID_CAMERAACTION_DEBUG = 21,
    NFSMW_ActionID_CAMERAACTION_ENABLE_ICE = 22,
    NFSMW_ActionID_CAMERAACTION_LOOKBACK = 23,
    NFSMW_ActionID_CAMERAACTION_PULLBACK = 24,
    NFSMW_ActionID_FRONTENDACTION_UP = 25,
    NFSMW_ActionID_FRONTENDACTION_DOWN = 26,
    NFSMW_ActionID_FRONTENDACTION_LEFT = 27,
    NFSMW_ActionID_FRONTENDACTION_RIGHT = 28,
    NFSMW_ActionID_FRONTENDACTION_RUP = 29,
    NFSMW_ActionID_FRONTENDACTION_RDOWN = 30,
    NFSMW_ActionID_FRONTENDACTION_RLEFT = 31,
    NFSMW_ActionID_FRONTENDACTION_RRIGHT = 32,
    NFSMW_ActionID_FRONTENDACTION_ACCEPT = 33,
    NFSMW_ActionID_FRONTENDACTION_CANCEL = 34,
    NFSMW_ActionID_FRONTENDACTION_CANCEL_ALT = 35,
    NFSMW_ActionID_FRONTENDACTION_START = 36,
    NFSMW_ActionID_FRONTENDACTION_BUTTON0 = 37,
    NFSMW_ActionID_FRONTENDACTION_BUTTON1 = 38,
    NFSMW_ActionID_FRONTENDACTION_BUTTON2 = 39,
    NFSMW_ActionID_FRONTENDACTION_BUTTON3 = 40,
    NFSMW_ActionID_FRONTENDACTION_BUTTON4 = 41,
    NFSMW_ActionID_FRONTENDACTION_BUTTON5 = 42,
    NFSMW_ActionID_FRONTENDACTION_LTRIGGER = 43,
    NFSMW_ActionID_FRONTENDACTION_RTRIGGER = 44,
    NFSMW_ActionID_HUDACTION_PAUSEREQUEST = 45,
    NFSMW_ActionID_HUDACTION_ENGAGE_EVENT = 46,
    NFSMW_ActionID_HUDACTION_PAD_LEFT = 47,
    NFSMW_ActionID_HUDACTION_PAD_DOWN = 48,
    NFSMW_ActionID_HUDACTION_PAD_RIGHT = 49,
    NFSMW_ActionID_HUDACTION_SKIPNIS = 50,
    NFSMW_ActionID_HUDACTION_NEXTSONG = 51,
    NFSMW_ActionID_VOIPACTION_PUSHTOTALK = 52,
    NFSMW_ActionID_DEBUGACTION_MOVE_UP = 53,
    NFSMW_ActionID_DEBUGACTION_MOVE_DOWN = 54,
    NFSMW_ActionID_DEBUGACTION_MOVE_LEFT = 55,
    NFSMW_ActionID_DEBUGACTION_MOVE_RIGHT = 56,
    NFSMW_ActionID_DEBUGACTION_MOVE_FORWARD = 57,
    NFSMW_ActionID_DEBUGACTION_MOVE_BACK = 58,
    NFSMW_ActionID_DEBUGACTION_MOVE_D_LEFT = 59,
    NFSMW_ActionID_DEBUGACTION_MOVE_D_RIGHT = 60,
    NFSMW_ActionID_DEBUGACTION_MOVE_D_FORWARD = 61,
    NFSMW_ActionID_DEBUGACTION_MOVE_D_BACK = 62,
    NFSMW_ActionID_DEBUGACTION_LOOK_UP = 63,
    NFSMW_ActionID_DEBUGACTION_LOOK_DOWN = 64,
    NFSMW_ActionID_DEBUGACTION_LOOK_LEFT = 65,
    NFSMW_ActionID_DEBUGACTION_LOOK_RIGHT = 66,
    NFSMW_ActionID_DEBUGACTION_LOOK_D_UP = 67,
    NFSMW_ActionID_DEBUGACTION_LOOK_D_DOWN = 68,
    NFSMW_ActionID_DEBUGACTION_LOOK_D_LEFT = 69,
    NFSMW_ActionID_DEBUGACTION_LOOK_D_RIGHT = 70,
    NFSMW_ActionID_DEBUGACTION_TURBO = 71,
    NFSMW_ActionID_DEBUGACTION_SUPER_TURBO = 72,
    NFSMW_ActionID_DEBUGACTION_DROPCAR = 73,
    NFSMW_ActionID_DEBUGACTION_TOGGLEAI = 74,
    NFSMW_ActionID_DEBUGACTION_TOGGLESIMSTEP = 75,
    NFSMW_ActionID_DEBUGACTION_SIMSTEP = 76,
    NFSMW_ActionID_DEBUGACTION_SCREENSHOT = 77,
    NFSMW_ActionID_DEBUGACTION_STOPRECORDPATH = 78,
    NFSMW_ActionID_DEBUGACTION_TOGGLECARCOLOUR = 79,
    NFSMW_ActionID_DEBUGACTION_TOGGLEDEMOCAMERAS = 80,
    NFSMW_ActionID_ICEACTION_GRAB_LEFT = 81,
    NFSMW_ActionID_ICEACTION_GRAB_RIGHT = 82,
    NFSMW_ActionID_ICEACTION_LEFT = 83,
    NFSMW_ActionID_ICEACTION_RIGHT = 84,
    NFSMW_ActionID_ICEACTION_FAST_LEFT = 85,
    NFSMW_ActionID_ICEACTION_FAST_RIGHT = 86,
    NFSMW_ActionID_ICEACTION_UP = 87,
    NFSMW_ActionID_ICEACTION_DOWN = 88,
    NFSMW_ActionID_ICEACTION_HELP = 89,
    NFSMW_ActionID_ICEACTION_UNDO = 90,
    NFSMW_ActionID_ICEACTION_PLAY = 91,
    NFSMW_ActionID_ICEACTION_HIDE = 92,
    NFSMW_ActionID_ICEACTION_SCREENSHOT = 93,
    NFSMW_ActionID_ICEACTION_SCREENSHOT_STREAM = 94,
    NFSMW_ActionID_ICEACTION_INSERT = 95,
    NFSMW_ActionID_ICEACTION_CUT = 96,
    NFSMW_ActionID_ICEACTION_COPY = 97,
    NFSMW_ActionID_ICEACTION_PASTE = 98,
    NFSMW_ActionID_ICEACTION_SELECT = 99,
    NFSMW_ActionID_ICEACTION_CANCEL = 100,
    NFSMW_ActionID_ICEACTION_ALT_1 = 101,
    NFSMW_ActionID_ICEACTION_CLIP_IN = 102,
    NFSMW_ActionID_ICEACTION_CLIP_OUT = 103,
    NFSMW_ActionID_ICEACTION_SIMSPEED_INC = 104,
    NFSMW_ActionID_ICEACTION_SIMSPEED_DEC = 105,
    NFSMW_ActionID_ICEACTION_DUTCH_LEFT = 106,
    NFSMW_ActionID_ICEACTION_DUTCH_RIGHT = 107,
    NFSMW_ActionID_ICEACTION_ZOOM_IN = 108,
    NFSMW_ActionID_ICEACTION_ZOOM_OUT = 109,
    NFSMW_ActionID_ICEACTION_LETTERBOX_IN = 110,
    NFSMW_ActionID_ICEACTION_LETTERBOX_OUT = 111,
    NFSMW_ActionID_ICEACTION_BUBBLE_IN = 112,
    NFSMW_ActionID_ICEACTION_BUBBLE_OUT = 113,
    NFSMW_ActionID_ICEACTION_BUBBLE_UP = 114,
    NFSMW_ActionID_ICEACTION_BUBBLE_DOWN = 115,
    NFSMW_ActionID_ICEACTION_BUBBLE_TILT_UP = 116,
    NFSMW_ActionID_ICEACTION_BUBBLE_TILT_DOWN = 117,
    NFSMW_ActionID_ICEACTION_BUBBLE_SPIN_LEFT = 118,
    NFSMW_ActionID_ICEACTION_BUBBLE_SPIN_RIGHT = 119,
    NFSMW_ActionID_ICEACTION_BUBBLE_LEFT = 120,
    NFSMW_ActionID_ICEACTION_BUBBLE_RIGHT = 121,
    NFSMW_ActionID_ICEACTION_BUBBLE_BACK = 122,
    NFSMW_ActionID_ICEACTION_BUBBLE_FORTH = 123,
    NFSMW_ActionID_ICEACTION_SHAKE_MAG_DEC = 124,
    NFSMW_ActionID_ICEACTION_SHAKE_MAG_INC = 125,
    NFSMW_ActionID_ICEACTION_SHAKE_FRQ_DEC = 126,
    NFSMW_ActionID_ICEACTION_SHAKE_FRQ_INC = 127,
    NFSMW_ActionID_ICEACTION_SHUTTLE_LEFT = 128,
    NFSMW_ActionID_ICEACTION_SHUTTLE_RIGHT = 129,
    NFSMW_ActionID_ICEACTION_SHUTTLE_UP = 130,
    NFSMW_ActionID_ICEACTION_SHUTTLE_DOWN = 131,
    NFSMW_ActionID_ICEACTION_SHUTTLE_SPEED_DEC = 132,
    NFSMW_ActionID_ICEACTION_SHUTTLE_SPEED_INC = 133,
    NFSMW_ActionID_ACTION_EXITAPPLICATION = 134,
    NFSMW_ActionID_ACTION_PLUGGED = 135,
    NFSMW_ActionID_ACTION_UNPLUGGED = 136,
    NFSMW_ActionID_ACTION_FLUSH = 137,
} NFSMW_ActionID;

typedef enum NFSMW_BodyFlags {
    NFSMW_BodyFlags_None = 0,
    NFSMW_BodyFlags_SkipSRBCollisions = 1 << 0,
    NFSMW_BodyFlags_SkipRBCollisions = 1 << 1,
    NFSMW_BodyFlags_SkipCollisions = 3,
    NFSMW_BodyFlags_ApplyBasicPhysics = 1 << 2,
    NFSMW_BodyFlags_LinearMotion = 1 << 3,
    NFSMW_BodyFlags_OBBCollideWith_RB = 1 << 6,
    NFSMW_BodyFlags_OBBCollideWith_SRB = 1 << 7,
    NFSMW_BodyFlags_CanHitTriggers = 1 << 8,
    NFSMW_BodyFlags_AngularMotion = 1 << 9,
    NFSMW_BodyFlags_SkipSameTypeCollisions = 1 << 14,
    NFSMW_BodyFlags_SOBBCollideWith_RB = 1 << 15,
} NFSMW_BodyFlags;

typedef enum NFSMW_CarSlotId {
    NFSMW_CarSlotId_Base = 0,
    NFSMW_CarSlotId_DamageModel_FrontWindow = 1,
    NFSMW_CarSlotId_DamageModel_Body = 2,
    NFSMW_CarSlotId_DamageModel_CopLights = 3,
    NFSMW_CarSlotId_DamageModel_CopSpoiler = 4,
    NFSMW_CarSlotId_DamageModel_FrontWheel = 5,
    NFSMW_CarSlotId_DamageModel_LeftBrakelight = 6,
    NFSMW_CarSlotId_DamageModel_RightBrakelight = 7,
    NFSMW_CarSlotId_DamageModel_LeftHeadlight = 8,
    NFSMW_CarSlotId_DamageModel_RightHeadlight = 9,
    NFSMW_CarSlotId_DamageModel_Hood = 10,
    NFSMW_CarSlotId_DamageModel_Bushguard = 11,
    NFSMW_CarSlotId_DamageModel_FrontBumper = 12,
    NFSMW_CarSlotId_DamageModel_RightDoor = 13,
    NFSMW_CarSlotId_DamageModel_RightRearDoor = 14,
    NFSMW_CarSlotId_DamageModel_Trunk = 15,
    NFSMW_CarSlotId_DamageModel_RearBumper = 16,
    NFSMW_CarSlotId_DamageModel_RearKeftWindow = 17,
    NFSMW_CarSlotId_DamageModel_FrontLeftWindow = 18,
    NFSMW_CarSlotId_DamageModel_FrontRightWindow = 19,
    NFSMW_CarSlotId_DamageModel_RearRightWindow = 20,
    NFSMW_CarSlotId_DamageModel_LeftDoor = 21,
    NFSMW_CarSlotId_DamageModel_LeftRearDoor = 22,
    NFSMW_CarSlotId_Body = 23,
    NFSMW_CarSlotId_FrontBrake = 24,
    NFSMW_CarSlotId_FrontLeftWindow = 25,
    NFSMW_CarSlotId_FrontRightWindow = 26,
    NFSMW_CarSlotId_FrontWindow = 27,
    NFSMW_CarSlotId_Interior = 28,
    NFSMW_CarSlotId_LeftBrakelight = 29,
    NFSMW_CarSlotId_LeftBrakelightGlass = 30,
    NFSMW_CarSlotId_LeftHeadlight = 31,
    NFSMW_CarSlotId_LeftHeadlightGlass = 32,
    NFSMW_CarSlotId_LeftSideMirror = 33,
    NFSMW_CarSlotId_RearBrake = 34,
    NFSMW_CarSlotId_RearLeftWindow = 35,
    NFSMW_CarSlotId_RearRightWindow = 36,
    NFSMW_CarSlotId_RearWindow = 37,
    NFSMW_CarSlotId_RightBrakelight = 38,
    NFSMW_CarSlotId_RightBrakelightGlass = 39,
    NFSMW_CarSlotId_RightHeadlight = 40,
    NFSMW_CarSlotId_RightHeadlightGlass = 41,
    NFSMW_CarSlotId_RightSideMirror = 42,
    NFSMW_CarSlotId_Driver = 43,
    NFSMW_CarSlotId_Spoiler = 44,
    NFSMW_CarSlotId_UniversalSpoilerBase = 45,
    NFSMW_CarSlotId_DamagePlayerModel_Front = 46,
    NFSMW_CarSlotId_DamagePlayerModel_FrontLeft = 47,
    NFSMW_CarSlotId_DamagePlayerModel_FrontRight = 48,
    NFSMW_CarSlotId_DamagePlayerModel_Rear = 49,
    NFSMW_CarSlotId_DamagePlayerModel_RearLeft = 50,
    NFSMW_CarSlotId_DamagePlayerModel_RearRight = 51,
    NFSMW_CarSlotId_Attachment0 = 52,
    NFSMW_CarSlotId_Attachment1 = 53,
    NFSMW_CarSlotId_Attachment2 = 54,
    NFSMW_CarSlotId_Attachment3 = 55,
    NFSMW_CarSlotId_Attachment4 = 56,
    NFSMW_CarSlotId_Attachment5 = 57,
    NFSMW_CarSlotId_Attachment6 = 58,
    NFSMW_CarSlotId_Attachment7 = 59,
    NFSMW_CarSlotId_Attachment8 = 60,
    NFSMW_CarSlotId_Attachment9 = 61,
    NFSMW_CarSlotId_RoofScoop = 62,
    NFSMW_CarSlotId_Hood = 63,
    NFSMW_CarSlotId_Headlight = 64,
    NFSMW_CarSlotId_Brakelight = 65,
    NFSMW_CarSlotId_FrontWheel = 66,
    NFSMW_CarSlotId_RearWheel = 67,
    NFSMW_CarSlotId_Spinner = 68,
    NFSMW_CarSlotId_LicensePlate = 69,
    NFSMW_CarSlotId_DecalModel_FrontWindow = 70,
    NFSMW_CarSlotId_DecalModel_RearWindow = 71,
    NFSMW_CarSlotId_DecalModel_LeftDoor = 72,
    NFSMW_CarSlotId_DecalModel_RightDoor = 73,
    NFSMW_CarSlotId_DecalModel_LeftQuarter = 74,
    NFSMW_CarSlotId_DecalModel_RightQuarter = 75,
    NFSMW_CarSlotId_BasePaint = 76,
    NFSMW_CarSlotId_VinylLayer = 77,
    NFSMW_CarSlotId_PaintRim = 78,
    NFSMW_CarSlotId_VinylColour0 = 79,
    NFSMW_CarSlotId_VinylColour1 = 80,
    NFSMW_CarSlotId_VinylColour2 = 81,
    NFSMW_CarSlotId_VinylColour3 = 82,
    NFSMW_CarSlotId_DecalTexture_FrontWindow0 = 83,
    NFSMW_CarSlotId_DecalTexture_FrontWindow1 = 84,
    NFSMW_CarSlotId_DecalTexture_FrontWindow2 = 85,
    NFSMW_CarSlotId_DecalTexture_FrontWindow3 = 86,
    NFSMW_CarSlotId_DecalTexture_FrontWindow4 = 87,
    NFSMW_CarSlotId_DecalTexture_FrontWindow5 = 88,
    NFSMW_CarSlotId_DecalTexture_FrontWindow6 = 89,
    NFSMW_CarSlotId_DecalTexture_FrontWindow7 = 90,
    NFSMW_CarSlotId_DecalTexture_RearWindow0 = 91,
    NFSMW_CarSlotId_DecalTexture_RearWindow1 = 92,
    NFSMW_CarSlotId_DecalTexture_RearWindow2 = 93,
    NFSMW_CarSlotId_DecalTexture_RearWindow3 = 94,
    NFSMW_CarSlotId_DecalTexture_RearWindow4 = 95,
    NFSMW_CarSlotId_DecalTexture_RearWindow5 = 96,
    NFSMW_CarSlotId_DecalTexture_RearWindow6 = 97,
    NFSMW_CarSlotId_DecalTexture_RearWindow7 = 98,
    NFSMW_CarSlotId_DecalTexture_LeftDoor0 = 99,
    NFSMW_CarSlotId_DecalTexture_LeftDoor1 = 100,
    NFSMW_CarSlotId_DecalTexture_LeftDoor2 = 101,
    NFSMW_CarSlotId_DecalTexture_LeftDoor3 = 102,
    NFSMW_CarSlotId_DecalTexture_LeftDoor4 = 103,
    NFSMW_CarSlotId_DecalTexture_LeftDoor5 = 104,
    NFSMW_CarSlotId_DecalTexture_LeftDoor_LeftNumber = 105,
    NFSMW_CarSlotId_DecalTexture_LeftDoor6 = 106,
    NFSMW_CarSlotId_DecalTexture_LeftDoor_RightNumber = 107,
    NFSMW_CarSlotId_DecalTexture_LeftDoor7 = 108,
    NFSMW_CarSlotId_DecalTexture_RightDoor0 = 109,
    NFSMW_CarSlotId_DecalTexture_RightDoor1 = 110,
    NFSMW_CarSlotId_DecalTexture_RightDoor2 = 111,
    NFSMW_CarSlotId_DecalTexture_RightDoor3 = 112,
    NFSMW_CarSlotId_DecalTexture_RightDoor4 = 113,
    NFSMW_CarSlotId_DecalTexture_RightDoor5 = 114,
    NFSMW_CarSlotId_DecalTexture_RightDoor_LeftNumber = 115,
    NFSMW_CarSlotId_DecalTexture_RightDoor6 = 116,
    NFSMW_CarSlotId_DecalTexture_RightDoor_RightNumber = 117,
    NFSMW_CarSlotId_DecalTexture_RightDoor7 = 118,
    NFSMW_CarSlotId_DecalTexture_LeftQuarter0 = 119,
    NFSMW_CarSlotId_DecalTexture_LeftQuarter1 = 120,
    NFSMW_CarSlotId_DecalTexture_LeftQuarter2 = 121,
    NFSMW_CarSlotId_DecalTexture_LeftQuarter3 = 122,
    NFSMW_CarSlotId_DecalTexture_LeftQuarter4 = 123,
    NFSMW_CarSlotId_DecalTexture_LeftQuarter5 = 124,
    NFSMW_CarSlotId_DecalTexture_LeftQuarter6 = 125,
    NFSMW_CarSlotId_DecalTexture_LeftQuarter7 = 126,
    NFSMW_CarSlotId_DecalTexture_RightQuarter_tex0 = 127,
    NFSMW_CarSlotId_DecalTexture_RightQuarter_tex1 = 128,
    NFSMW_CarSlotId_DecalTexture_RightQuarter_tex2 = 129,
    NFSMW_CarSlotId_DecalTexture_RightQuarter_tex3 = 130,
    NFSMW_CarSlotId_DecalTexture_RightQuarter_tex4 = 131,
    NFSMW_CarSlotId_DecalTexture_RightQuarter_tex5 = 132,
    NFSMW_CarSlotId_DecalTexture_RightQuarter_tex6 = 133,
    NFSMW_CarSlotId_DecalTexture_RightQuarter_tex7 = 134,
    NFSMW_CarSlotId_WindowTint = 135,
    NFSMW_CarSlotId_CustomHud = 136,
    NFSMW_CarSlotId_HudBackingColour = 137,
    NFSMW_CarSlotId_HudNeedleColour = 138,
    NFSMW_CarSlotId_HudCharacterColour = 139,
    NFSMW_CarSlotId_CV = 140,
    NFSMW_CarSlotId_WheelManufacturer = 141,
    NFSMW_CarSlotId_Misc = 142,
} NFSMW_CarSlotId;

typedef enum NFSMW_CarType {
    NFSMW_CarType_PORSCHE911TURBO = 0,
    NFSMW_CarType_PORSCHECARRERAGT = 1,
    NFSMW_CarType_VIPER = 2,
    NFSMW_CarType_COPMIDSIZE = 3,
    NFSMW_CarType_COPHELI = 4,
    NFSMW_CarType_RX8 = 5,
    NFSMW_CarType_IMPREZAWRX = 6,
    NFSMW_CarType_LANCEREVO8 = 7,
    NFSMW_CarType_MUSTANGGT = 8,
    NFSMW_CarType_CAMARO = 9,
    NFSMW_CarType_SEMI = 10,
    NFSMW_CarType_GTO = 11,
    NFSMW_CarType_SLR = 12,
    NFSMW_CarType_TRAILERA = 13,
    NFSMW_CarType_TRAILERB = 14,
    NFSMW_CarType_CORVETTE = 15,
    NFSMW_CarType_TRAFHA = 16,
    NFSMW_CarType_TRAFSUVA = 17,
    NFSMW_CarType_TRAF4DSEDB = 18,
    NFSMW_CarType_TRAFFICCOUP = 19,
    NFSMW_CarType_TT = 20,
    NFSMW_CarType_A3 = 21,
    NFSMW_CarType_BMWM3GTR = 22,
    NFSMW_CarType_SL500 = 23,
    NFSMW_CarType_PORSCHE997S = 24,
    NFSMW_CarType_TRAF4DSEDA = 25,
    NFSMW_CarType_TRAF4DSEDC = 26,
    NFSMW_CarType_TRAFCAMPER = 27,
    NFSMW_CarType_TRAFCEMTR = 28,
    NFSMW_CarType_TRAFDMPTR = 29,
    NFSMW_CarType_TRAFFIRE = 30,
    NFSMW_CarType_TRAFGARB = 31,
    NFSMW_CarType_TRAFMINIVAN = 32,
    NFSMW_CarType_TRAFNEWS = 33,
    NFSMW_CarType_TRAFPICKUPA = 34,
    NFSMW_CarType_TRAFSTWAG = 35,
    NFSMW_CarType_TRAFVANB = 36,
    NFSMW_CarType_TRAFTAXI = 37,
    NFSMW_CarType_TRAFCOURT = 38,
    NFSMW_CarType_TRAFPIZZA = 39,
    NFSMW_CarType_PORSCHE911GT2 = 40,
    NFSMW_CarType_BMWM3GTRE46 = 41,
    NFSMW_CarType_TRAFAMB = 42,
    NFSMW_CarType_TRAILERLOG = 43,
    NFSMW_CarType_TRAILERCON = 44,
    NFSMW_CarType_TRAILERCRATE = 45,
    NFSMW_CarType_TRAILERCMT = 46,
    NFSMW_CarType_IS300 = 47,
    NFSMW_CarType_MONARO = 48,
    NFSMW_CarType_SL65 = 49,
    NFSMW_CarType_ELISE = 50,
    NFSMW_CarType_COPMIDSIZEINT = 51,
    NFSMW_CarType_FORDGT = 52,
    NFSMW_CarType_ECLIPSEGT = 53,
    NFSMW_CarType_SUPRA = 54,
    NFSMW_CarType_CORVETTEC6R = 55,
    NFSMW_CarType_RX7 = 56,
    NFSMW_CarType_COPSUV = 57,
    NFSMW_CarType_RX8SPEEDT = 58,
    NFSMW_CarType_MURCIELAGO = 59,
    NFSMW_CarType_A4 = 60,
    NFSMW_CarType_COPSPORT = 61,
    NFSMW_CarType_GTI = 62,
    NFSMW_CarType_CAYMANS = 63,
    NFSMW_CarType_CLK500 = 64,
    NFSMW_CarType_CTS = 65,
    NFSMW_CarType_DB9 = 66,
    NFSMW_CarType_GALLARDO = 67,
    NFSMW_CarType_COBALTSS = 68,
    NFSMW_CarType_BMWM3 = 69,
    NFSMW_CarType_CLIO = 70,
    NFSMW_CarType_COPGHOST = 71,
    NFSMW_CarType_COPSUVL = 72,
    NFSMW_CarType_COPGTO = 73,
    NFSMW_CarType_PUNTO = 74,
    NFSMW_CarType_COPGTOGHOST = 75,
    NFSMW_CarType_COPSPORTHENCH = 76,
    NFSMW_CarType_COPSPORTGHOST = 77,
    NFSMW_CarType_CEMTR = 78,
    NFSMW_CarType_GARB = 79,
    NFSMW_CarType_PIZZA = 80,
    NFSMW_CarType_TAXI = 81,
    NFSMW_CarType_MINIVAN = 82,
    NFSMW_CarType_PICKUPA = 83,
    NFSMW_CarType_NONE = 0xFFFFFFFFu,
} NFSMW_CarType;

typedef enum NFSMW_CarType_pvehiclelayout {
    NFSMW_CarType_pvehiclelayout_McLaren = 1 << 0,
    NFSMW_CarType_pvehiclelayout_Porsche = 1 << 1,
    NFSMW_CarType_pvehiclelayout_FordGT = 1 << 2,
    NFSMW_CarType_pvehiclelayout_Viper = 1 << 3,
    NFSMW_CarType_pvehiclelayout_AstonMartin = 1 << 4,
    NFSMW_CarType_pvehiclelayout_Corvette = 1 << 5,
    NFSMW_CarType_pvehiclelayout_BMW = 1 << 6,
    NFSMW_CarType_pvehiclelayout_Mercedes = 1 << 7,
    NFSMW_CarType_pvehiclelayout_Audi = 1 << 8,
    NFSMW_CarType_pvehiclelayout_Mitsubishi = 1 << 9,
    NFSMW_CarType_pvehiclelayout_Mustang = 1 << 10,
    NFSMW_CarType_pvehiclelayout_Lotus = 1 << 11,
    NFSMW_CarType_pvehiclelayout_Subaru = 1 << 12,
    NFSMW_CarType_pvehiclelayout_Camaro = 1 << 13,
    NFSMW_CarType_pvehiclelayout_GTO = 1 << 14,
    NFSMW_CarType_pvehiclelayout_Nissan = 1 << 15,
    NFSMW_CarType_pvehiclelayout_Mazda = 1 << 16,
    NFSMW_CarType_pvehiclelayout_Renault = 1 << 17,
    NFSMW_CarType_pvehiclelayout_Lexus = 1 << 18,
    NFSMW_CarType_pvehiclelayout_Mini = 1 << 19,
    NFSMW_CarType_pvehiclelayout_Volkswagen = 1 << 20,
    NFSMW_CarType_pvehiclelayout_SUV = 1 << 21,
    NFSMW_CarType_pvehiclelayout_Pickup = 1 << 22,
    NFSMW_CarType_pvehiclelayout_Pagani = 1 << 23,
    NFSMW_CarType_pvehiclelayout_Lamborghini = 1 << 24,
    NFSMW_CarType_pvehiclelayout_Chrysler = 1 << 25,
    NFSMW_CarType_pvehiclelayout_Opel = 1 << 26,
    NFSMW_CarType_pvehiclelayout_Sedan = 1 << 27,
    NFSMW_CarType_pvehiclelayout_SportsCar = 1 << 28,
    NFSMW_CarType_pvehiclelayout_Supra = 1 << 29,
    NFSMW_CarType_pvehiclelayout_Cadillac = 1 << 30,
} NFSMW_CarType_pvehiclelayout;

typedef enum NFSMW_CarUsageType {
    NFSMW_CarUsageType_Racing = 0,
    NFSMW_CarUsageType_Cop = 1,
    NFSMW_CarUsageType_Traffic = 2,
    NFSMW_CarUsageType_Wheels = 3,
    NFSMW_CarUsageType_Universal = 4,
} NFSMW_CarUsageType;

typedef enum NFSMW_CollisionType {
    NFSMW_CollisionType_None = 0,
    NFSMW_CollisionType_Object = 1,
    NFSMW_CollisionType_World = 2,
    NFSMW_CollisionType_Ground = 3,
} NFSMW_CollisionType;

typedef enum NFSMW_Context {
    NFSMW_Context_QuickRace = 0,
    NFSMW_Context_Online = 1,
    NFSMW_Context_Career = 2,
} NFSMW_Context;

typedef enum NFSMW_DriveFlags {
    NFSMW_DriveFlags_Steer = 1 << 0,
    NFSMW_DriveFlags_GasBrake = 1 << 1,
    NFSMW_DriveFlags_Reverse = 1 << 2,
    NFSMW_DriveFlags_All = NFSMW_DriveFlags_Steer | NFSMW_DriveFlags_GasBrake | NFSMW_DriveFlags_Reverse,
} NFSMW_DriveFlags;

typedef enum NFSMW_DriverClass {
    NFSMW_DriverClass_Human = 0,
    NFSMW_DriverClass_Traffic = 1,
    NFSMW_DriverClass_Cop = 2,
    NFSMW_DriverClass_Racer = 3,
    NFSMW_DriverClass_None = 4,
    NFSMW_DriverClass_NIS = 5,
    NFSMW_DriverClass_Remote = 6,
} NFSMW_DriverClass;

typedef enum NFSMW_DriverStyle {
    NFSMW_DriverStyle_Racing = 0,
    NFSMW_DriverStyle_Drag = 1,
} NFSMW_DriverStyle;

typedef enum NFSMW_FEngTypes {
    NFSMW_FEngTypes_None = 0,
    NFSMW_FEngTypes_Type1 = 0x8AB83EDB,
    NFSMW_FEngTypes_Type2 = 0x9D73BC15,
    NFSMW_FEngTypes_Type3 = 0x5230FAF6,
    NFSMW_FEngTypes_Type4 = 0xA19BB14C,
    NFSMW_FEngTypes_Type5 = 0x821E6378,
} NFSMW_FEngTypes;

typedef enum NFSMW_Flags {
    NFSMW_Flags_Array = 1 << 0,
    NFSMW_Flags_InLayout = 1 << 1,
    NFSMW_Flags_IsBound = 1 << 2,
    NFSMW_Flags_IsNotSearchable = 1 << 3,
} NFSMW_Flags;

typedef enum NFSMW_Flags_Instance {
    NFSMW_Flags_Instance_Dynamic = 1,
} NFSMW_Flags_Instance;

typedef enum NFSMW_Flags_GCharacter {
    NFSMW_Flags_GCharacter_UsingStockCar = 0,
    NFSMW_Flags_GCharacter_AttachedToManager = 1,
} NFSMW_Flags_GCharacter;

typedef enum NFSMW_Flags_GIcon {
    NFSMW_Flags_GIcon_ShowInWorld = 1 << 0,
    NFSMW_Flags_GIcon_ShowOnMap = 1 << 1,
    NFSMW_Flags_GIcon_Spawned = 1 << 2,
    NFSMW_Flags_GIcon_Enabled = 1 << 3,
    NFSMW_Flags_GIcon_Disposable = 1 << 4,
    NFSMW_Flags_GIcon_SnappedToGround = 1 << 5,
    NFSMW_Flags_GIcon_ShowOnSpawn = 1 << 6,
    NFSMW_Flags_GIcon_GPSing = 1 << 7,
} NFSMW_Flags_GIcon;

typedef enum NFSMW_Flags_RacePreparationInfo {
    NFSMW_Flags_RacePreparationInfo_NONE = 0,
    NFSMW_Flags_RacePreparationInfo_RESET_DAMAGE = 1,
} NFSMW_Flags_RacePreparationInfo;

typedef enum NFSMW_Flags_ResetCar {
    NFSMW_Flags_ResetCar_None = 0,
    NFSMW_Flags_ResetCar_FindRoad = 1,
} NFSMW_Flags_ResetCar;

typedef enum NFSMW_Flags_RigidBody {
    NFSMW_Flags_RigidBody_VSWORLD = 1 << 0,
    NFSMW_Flags_RigidBody_VSOBJECTS = 1 << 1,
    NFSMW_Flags_RigidBody_VSGROUND = 1 << 2,
    NFSMW_Flags_RigidBody_DISABLED = 1 << 3,
    NFSMW_Flags_RigidBody_ONESIDED = 1 << 4,
} NFSMW_Flags_RigidBody;

typedef enum NFSMW_Flags_2 {
    NFSMW_Flags_2_DISABLED = 1 << 0,
    NFSMW_Flags_2_FREEABLE = 1 << 2,
} NFSMW_Flags_2;

typedef enum NFSMW_ForceStopType {
    NFSMW_ForceStopType_ForceStop = 1 << 0,
    NFSMW_ForceStopType_InstantStop = 1 << 1,
    NFSMW_ForceStopType_ForceCoast = 1 << 2,
    NFSMW_ForceStopType_StopOnline = 1 << 4,
} NFSMW_ForceStopType;

typedef enum NFSMW_GearID {
    NFSMW_GearID_Reverse = 0,
    NFSMW_GearID_Neutral = 1,
    NFSMW_GearID_First = 2,
    NFSMW_GearID_Second = 3,
    NFSMW_GearID_Third = 4,
    NFSMW_GearID_Fourth = 5,
    NFSMW_GearID_Fifth = 6,
    NFSMW_GearID_Sixth = 7,
    NFSMW_GearID_Seventh = 8,
    NFSMW_GearID_Eighth = 9,
} NFSMW_GearID;

typedef enum NFSMW_ID {
    NFSMW_ID_Front = 0,
    NFSMW_ID_Rear = 1,
    NFSMW_ID_Left = 2,
    NFSMW_ID_Right = 3,
    NFSMW_ID_LeftFront = 4,
    NFSMW_ID_RightFront = 5,
    NFSMW_ID_LeftRear = 6,
    NFSMW_ID_RightRear = 7,
    NFSMW_ID_Top = 8,
    NFSMW_ID_Bottom = 9,
} NFSMW_ID;

typedef enum NFSMW_IconDisplayTypes {
    NFSMW_IconDisplayTypes_HideIcon = 0,
    NFSMW_IconDisplayTypes_ShowIcon = 0x609F6B15,
} NFSMW_IconDisplayTypes;

typedef enum NFSMW_JunkmanParts {
    NFSMW_JunkmanParts_None = 0,
    NFSMW_JunkmanParts_Tires = 1 << 0,
    NFSMW_JunkmanParts_Brakes = 1 << 1,
    NFSMW_JunkmanParts_Chassis = 1 << 2,
    NFSMW_JunkmanParts_Transmission = 1 << 3,
    NFSMW_JunkmanParts_Engine = 1 << 4,
    NFSMW_JunkmanParts_Induction = 1 << 5,
    NFSMW_JunkmanParts_NOS = 1 << 6,
    NFSMW_JunkmanParts_All = (NFSMW_JunkmanParts_Tires) | (NFSMW_JunkmanParts_Brakes) | (NFSMW_JunkmanParts_Chassis) |
          (NFSMW_JunkmanParts_Transmission) | (NFSMW_JunkmanParts_Engine) |
          (NFSMW_JunkmanParts_Induction) | (NFSMW_JunkmanParts_NOS),
} NFSMW_JunkmanParts;

typedef enum NFSMW_Path {
    NFSMW_Path_Steering = 0,
    NFSMW_Path_Handling = 1,
    NFSMW_Path_Brakes = 2,
    NFSMW_Path_RideHeight = 3,
    NFSMW_Path_Aerodynamics = 4,
    NFSMW_Path_NOS = 5,
    NFSMW_Path_Induction = 6,
} NFSMW_Path;

typedef enum NFSMW_PlayMode {
    NFSMW_PlayMode_Roaming = 0,
    NFSMW_PlayMode_Racing = 1,
} NFSMW_PlayMode;

typedef enum NFSMW_Priority {
    NFSMW_Priority_Priority5 = 0,
    NFSMW_Priority_Priority4 = 1,
    NFSMW_Priority_Priority3 = 2,
    NFSMW_Priority_Priority2 = 3,
    NFSMW_Priority_Priority1 = 4,
} NFSMW_Priority;

typedef enum NFSMW_RaceType {
    NFSMW_RaceType_Point2Point = 0,
    NFSMW_RaceType_Circuit = 1,
    NFSMW_RaceType_Drag = 2,
    NFSMW_RaceType_Knockout = 3,
    NFSMW_RaceType_Tollbooth = 4,
    NFSMW_RaceType_SpeedTrap = 5,
    NFSMW_RaceType_Checkpoint = 6,
    NFSMW_RaceType_CashGrab = 7,
    NFSMW_RaceType_Challenge = 8,
    NFSMW_RaceType_JumpToSpeedTrap = 9,
    NFSMW_RaceType_JumpToMilestone = 10,
    NFSMW_RaceType_None = 0xFFFFFFFFu,
} NFSMW_RaceType;

typedef enum NFSMW_RaceTypes {
    NFSMW_RaceTypes_None = 0,
    NFSMW_RaceTypes_SingleRace = 1,
    NFSMW_RaceTypes_TimeTrial = 2,
    NFSMW_RaceTypes_LapKnockout = 3,
    NFSMW_RaceTypes_RaceRnockout = 4,
    NFSMW_RaceTypes_Tournament = 5,
    NFSMW_RaceTypes_CarShow = 6,
    NFSMW_RaceTypes_GetAway = 7,
} NFSMW_RaceTypes;

typedef enum NFSMW_Region {
    NFSMW_Region_College = 0,
    NFSMW_Region_Coastal = 1,
    NFSMW_Region_City = 2,
    NFSMW_Region_None = 0xFFu,
} NFSMW_Region;

typedef enum NFSMW_ShiftPotential {
    NFSMW_ShiftPotential_None = 0,
    NFSMW_ShiftPotential_Down = 1,
    NFSMW_ShiftPotential_Up = 2,
    NFSMW_ShiftPotential_Good = 3,
    NFSMW_ShiftPotential_Perfect = 4,
    NFSMW_ShiftPotential_Miss = 5,
} NFSMW_ShiftPotential;

typedef enum NFSMW_ShiftStatus {
    NFSMW_ShiftStatus_None = 0,
    NFSMW_ShiftStatus_Normal = 1,
    NFSMW_ShiftStatus_Good = 2,
    NFSMW_ShiftStatus_Perfect = 3,
    NFSMW_ShiftStatus_Missed = 4,
} NFSMW_ShiftStatus;

typedef enum NFSMW_SplineType {
    NFSMW_SplineType_Bezier = 0,
    NFSMW_SplineType_CatMulRom = 1,
    NFSMW_SplineType_Invalid = 2,
} NFSMW_SplineType;

typedef enum NFSMW_State {
    NFSMW_State_Invalid = 0,
    NFSMW_State_Unspawned = 1,
    NFSMW_State_SpawningWaitingForModel = 2,
    NFSMW_State_SpawningWaitingForTrack = 3,
    NFSMW_State_Spawned = 4,
    NFSMW_State_UnspawningWaitingUntilOffscreen = 5,
} NFSMW_State;

typedef enum NFSMW_Status {
    NFSMW_Status_NoTrigger = 1 << 0,
    NFSMW_Status_Attached = 1 << 1,
    NFSMW_Status_CollisionWorld = 1 << 2,
    NFSMW_Status_CollisionObject = 1 << 3,
    NFSMW_Status_EnableDrag = 1 << 5,
    NFSMW_Status_CheckWorld = 1 << 6,
    NFSMW_Status_FixedCG = 1 << 7,
    NFSMW_Status_Animating = 1 << 8,
    NFSMW_Status_Initiliazed = 1 << 9,
    NFSMW_Status_Integrating = 1 << 10,
    NFSMW_Status_EnableDragAngular = 1 << 11,
    NFSMW_Status_DisableIntegrator = 1 << 12,
    NFSMW_Status_ModifyPrims = 1 << 13,
    NFSMW_Status_Inactive = 1 << 14,
    NFSMW_Status_CollisionGround = 1 << 15,
} NFSMW_Status;

typedef enum NFSMW_TriggerFlags {
    NFSMW_TriggerFlags_Enabled = 1 << 0,
    NFSMW_TriggerFlags_OneShot = 1 << 1,
    NFSMW_TriggerFlags_PlayerActivated = 1 << 2,
    NFSMW_TriggerFlags_AIActivated = 1 << 3,
    NFSMW_TriggerFlags_ExplosionActivated = 1 << 4,
    NFSMW_TriggerFlags_VehicleActivated = 1 << 5,
    NFSMW_TriggerFlags_BodyActivated = 1 << 6,
    NFSMW_TriggerFlags_TimeActivated = 1 << 7,
    NFSMW_TriggerFlags_UnManaged = 1 << 8,
    NFSMW_TriggerFlags_PathAnimActivated = 1 << 9,
    NFSMW_TriggerFlags_Silencable = 1 << 10,
    NFSMW_TriggerFlags_UseEntry = 1 << 11,
    NFSMW_TriggerFlags_NonUpYVec = 1 << 12,
    NFSMW_TriggerFlags_PlayerCharActivated = 1 << 13,
    NFSMW_TriggerFlags_DebugOnly = 1 << 14,
    NFSMW_TriggerFlags_FireOnExit = 1 << 15,
    NFSMW_TriggerFlags_HumanActivated = 1 << 16,
    NFSMW_TriggerFlags_CopActivated = 1 << 17,
    NFSMW_TriggerFlags_FireOnEntry = 1 << 18,
} NFSMW_TriggerFlags;

typedef enum NFSMW_TriggerTypes {
    NFSMW_TriggerTypes_Undefined = 0,
    NFSMW_TriggerTypes_Standard = 1,
} NFSMW_TriggerTypes;

typedef enum NFSMW_Type {
    NFSMW_Type_Tires = 0,
    NFSMW_Type_Brakes = 1,
    NFSMW_Type_Chassis = 2,
    NFSMW_Type_Transmission = 3,
    NFSMW_Type_Engine = 4,
    NFSMW_Type_Induction = 5,
    NFSMW_Type_NOS = 6,
} NFSMW_Type;

typedef enum NFSMW_Type_GIcon {
    NFSMW_Type_GIcon_Invalid = 0,
    NFSMW_Type_GIcon_RaceSprint = 1,
    NFSMW_Type_GIcon_RaceCircuit = 2,
    NFSMW_Type_GIcon_RaceDrag = 3,
    NFSMW_Type_GIcon_RaceKnockout = 4,
    NFSMW_Type_GIcon_RaceCheckPoint = 5,
    NFSMW_Type_GIcon_RaceSpeedtrap = 6,
    NFSMW_Type_GIcon_RaceRival = 7,
    NFSMW_Type_GIcon_GateSafehouse = 8,
    NFSMW_Type_GIcon_GateCarLot = 9,
    NFSMW_Type_GIcon_GateCustomShop = 10,
    NFSMW_Type_GIcon_HidingSpot = 11,
    NFSMW_Type_GIcon_PursuitBreaker = 12,
    NFSMW_Type_GIcon_SpeedTrapInRace = 13,
    NFSMW_Type_GIcon_Checkpoint = 14,
    NFSMW_Type_GIcon_GoalMarker = 15,
} NFSMW_Type_GIcon;

typedef enum NFSMW_eAIDifficultyModifier {
    NFSMW_eAIDifficultyModifier_Easy = 0,
    NFSMW_eAIDifficultyModifier_SomewhatEasy = 1,
    NFSMW_eAIDifficultyModifier_Normal = 2,
} NFSMW_eAIDifficultyModifier;

typedef enum NFSMW_eCareerUpgradeLevels {
    NFSMW_eCareerUpgradeLevels_LevelStock = 0,
    NFSMW_eCareerUpgradeLevels_Level1 = 1,
    NFSMW_eCareerUpgradeLevels_Level2 = 2,
    NFSMW_eCareerUpgradeLevels_Level3 = 3,
    NFSMW_eCareerUpgradeLevels_LevelUnique = 4,
    NFSMW_eCareerUpgradeLevels_LevelUnspecified = 0xFFFFFFFFu,
} NFSMW_eCareerUpgradeLevels;

typedef enum NFSMW_eControllerConfig {
    NFSMW_eControllerConfig_MinConfig = 0,
    NFSMW_eControllerConfig_Config1 = 1,
    NFSMW_eControllerConfig_Config2 = 2,
    NFSMW_eControllerConfig_Config3 = 3,
    NFSMW_eControllerConfig_Config4 = 4,
    NFSMW_eControllerConfig_MaxConfig = 5,
    NFSMW_eControllerConfig_Config5 = 6,
} NFSMW_eControllerConfig;

typedef enum NFSMW_eCrossState {
    NFSMW_eCrossState_Available = 0,
    NFSMW_eCrossState_Spawned = 1,
    NFSMW_eCrossState_Disabled = 2,
} NFSMW_eCrossState;

typedef enum NFSMW_eDriftType {
    NFSMW_eDriftType_VsAI = 0,
    NFSMW_eDriftType_Downhill = 1,
    NFSMW_eDriftType_Team = 2,
} NFSMW_eDriftType;

typedef enum NFSMW_eFEGameModes {
    NFSMW_eFEGameModes_None = 0,
    NFSMW_eFEGameModes_Career = 1 << 0,
    NFSMW_eFEGameModes_Challenge = 1 << 1,
    NFSMW_eFEGameModes_QuickRace = 1 << 2,
    NFSMW_eFEGameModes_Online = 1 << 3,
    NFSMW_eFEGameModes_Options = 1 << 4,
    NFSMW_eFEGameModes_Customize = 1 << 5,
    NFSMW_eFEGameModes_Lan = 1 << 6,
    NFSMW_eFEGameModes_ProfileManager = 1 << 7,
    NFSMW_eFEGameModes_CareerManager = 1 << 8,
    NFSMW_eFEGameModes_RapSheet = 1 << 9,
    NFSMW_eFEGameModes_ModeSelect = 1 << 10,
    NFSMW_eFEGameModes_Trailers = 1 << 11,
    NFSMW_eFEGameModes_CarLot = 1 << 15,
    NFSMW_eFEGameModes_Safehouse = 1 << 16,
    NFSMW_eFEGameModes_PostRival = 1 << 17,
    NFSMW_eFEGameModes_BeatGame = 1 << 18,
} NFSMW_eFEGameModes;

typedef enum NFSMW_eFlags {
    NFSMW_eFlags_CutByObject = 1,
    NFSMW_eFlags_CutFromBehind = 2,
} NFSMW_eFlags;

typedef enum NFSMW_eImpoundReasons {
    NFSMW_eImpoundReasons_None = 0,
    NFSMW_eImpoundReasons_BustedByCross = 1,
    NFSMW_eImpoundReasons_StrikeLimitReached = 2,
    NFSMW_eImpoundReasons_InsufficientFunds = 3,
    NFSMW_eImpoundReasons_Released = 4,
} NFSMW_eImpoundReasons;

typedef enum NFSMW_eLoadSaveGame {
    NFSMW_eLoadSaveGame_Load = 0,
    NFSMW_eLoadSaveGame_Save = 1,
} NFSMW_eLoadSaveGame;

typedef enum NFSMW_eLocationName {
    NFSMW_eLocationName_UpperClass = 0,
    NFSMW_eLocationName_CityCore = 1,
    NFSMW_eLocationName_SuburbanHills = 2,
    NFSMW_eLocationName_IndustrialPark = 3,
    NFSMW_eLocationName_Airport = 4,
    NFSMW_eLocationName_ModeSpecific = 5,
} NFSMW_eLocationName;

typedef enum NFSMW_eMiniMapModes {
    NFSMW_eMiniMapModes_Static = 0,
    NFSMW_eMiniMapModes_Rotate = 1,
    NFSMW_eMiniMapModes_Off = 2,
} NFSMW_eMiniMapModes;

typedef enum NFSMW_eOpponentStrength {
    NFSMW_eOpponentStrength_Low = 0,
    NFSMW_eOpponentStrength_Medium = 1,
    NFSMW_eOpponentStrength_High = 2,
} NFSMW_eOpponentStrength;

typedef enum NFSMW_eOptionsCategory {
    NFSMW_eOptionsCategory_Audio = 0,
    NFSMW_eOptionsCategory_Video = 1,
    NFSMW_eOptionsCategory_PCAdvancedDisplay = 2,
    NFSMW_eOptionsCategory_Gameplay = 3,
    NFSMW_eOptionsCategory_Player = 4,
    NFSMW_eOptionsCategory_Controls = 5,
    NFSMW_eOptionsCategory_EATrax = 6,
    NFSMW_eOptionsCategory_Trailers = 7,
    NFSMW_eOptionsCategory_Credits = 8,
    NFSMW_eOptionsCategory_Online = 9,
} NFSMW_eOptionsCategory;

typedef enum NFSMW_ePlayerList {
    NFSMW_ePlayerList_All = 0,
    NFSMW_ePlayerList_Local = 1,
    NFSMW_ePlayerList_Remote = 2,
} NFSMW_ePlayerList;

typedef enum NFSMW_ePlayerSettingsCameras {
    NFSMW_ePlayerSettingsCameras_Bumper = 0,
    NFSMW_ePlayerSettingsCameras_Hood = 1,
    NFSMW_ePlayerSettingsCameras_Close = 2,
    NFSMW_ePlayerSettingsCameras_Far = 3,
    NFSMW_ePlayerSettingsCameras_SuperFar = 4,
    NFSMW_ePlayerSettingsCameras_Drift = 5,
    NFSMW_ePlayerSettingsCameras_Pursuit = 6,
    NFSMW_ePlayerSettingsCameras_Invalid = 0xFFFFFFFFu,
} NFSMW_ePlayerSettingsCameras;

typedef enum NFSMW_ePostRaceOptions {
    NFSMW_ePostRaceOptions_NextRace = 0,
    NFSMW_ePostRaceOptions_Quit = 1,
    NFSMW_ePostRaceOptions_RestartRace = 2,
    NFSMW_ePostRaceOptions_RestartEvent = 3,
} NFSMW_ePostRaceOptions;

typedef enum NFSMW_ePursuitStatus {
    NFSMW_ePursuitStatus_InitialChase = 0,
    NFSMW_ePursuitStatus_BackupRequested = 1,
    NFSMW_ePursuitStatus_Cooldown = 2,
    NFSMW_ePursuitStatus_Busted = 3,
    NFSMW_ePursuitStatus_Evaded = 4,
} NFSMW_ePursuitStatus;

typedef enum NFSMW_eSplitTimeTypes {
    NFSMW_eSplitTimeTypes_RaceLeader = 0,
    NFSMW_eSplitTimeTypes_LapRecord = 1,
    NFSMW_eSplitTimeTypes_BestLap = 2,
    NFSMW_eSplitTimeTypes_LastLap = 3,
    NFSMW_eSplitTimeTypes_Off = 4,
} NFSMW_eSplitTimeTypes;

typedef enum NFSMW_eState {
    NFSMW_eState_Disabled = 0,
    NFSMW_eState_Enabled = 1,
} NFSMW_eState;

typedef enum NFSMW_eTrackDifficulty {
    NFSMW_eTrackDifficulty_Easy = 0,
    NFSMW_eTrackDifficulty_Medium = 1,
    NFSMW_eTrackDifficulty_Hard = 2,
} NFSMW_eTrackDifficulty;

typedef enum NFSMW_eTrackDirection {
    NFSMW_eTrackDirection_Forward = 0,
    NFSMW_eTrackDirection_Backward = 1,
} NFSMW_eTrackDirection;

typedef enum NFSMW_eTransmissionType {
    NFSMW_eTransmissionType_Automatic = 0,
    NFSMW_eTransmissionType_Manual = 1,
    NFSMW_eTransmissionType_Sport = 2,
    NFSMW_eTransmissionType_ManualClutch = 3,
} NFSMW_eTransmissionType;

typedef enum NFSMW_eVehicleList {
    NFSMW_eVehicleList_All = 0,
    NFSMW_eVehicleList_Players = 1,
    NFSMW_eVehicleList_AI = 2,
    NFSMW_eVehicleList_AIRacers = 3,
    NFSMW_eVehicleList_AICops = 4,
    NFSMW_eVehicleList_AITraffic = 5,
    NFSMW_eVehicleList_Racers = 6,
    NFSMW_eVehicleList_Remote = 7,
    NFSMW_eVehicleList_Inactive = 8,
    NFSMW_eVehicleList_Trailers = 9,
} NFSMW_eVehicleList;

typedef enum NFSMW_eVehicleParamFlags {
    NFSMW_eVehicleParamFlags_None = 0,
    NFSMW_eVehicleParamFlags_Spooled = 1 << 0,
    NFSMW_eVehicleParamFlags_SnapToGround = 1 << 1,
    NFSMW_eVehicleParamFlags_NosRemoved = 1 << 2,
    NFSMW_eVehicleParamFlags_CalcPerformance = 1 << 3,
    NFSMW_eVehicleParamFlags_NosAdded = 1 << 4,
} NFSMW_eVehicleParamFlags;

typedef enum NFSMW_eWorldMapView {
    NFSMW_eWorldMapView_Navigation = 0,
    NFSMW_eWorldMapView_Event = 1,
    NFSMW_eWorldMapView_Race = 2,
    NFSMW_eWorldMapView_Pursuit = 3,
} NFSMW_eWorldMapView;

#endif
