/* AUTO-GENERATED by tools/codegen.py — DO NOT EDIT.
 * Source: docs/sdk_addrs.json */
#ifndef NFSMW_SDK_GENERATED_ADDRS_H
#define NFSMW_SDK_GENERATED_ADDRS_H

/* ---- globals (28) ---- */
#define NFSMW_GEN_G_AnimationSpeed 0x00904AECu  /* float */
#define NFSMW_GEN_G_CarScaleMatrix 0x009B34B0u  /* Math::Matrix4 */
#define NFSMW_GEN_G_DrawCarShadow 0x00903328u  /* bool */
#define NFSMW_GEN_G_DrawCars 0x00903320u  /* bool */
#define NFSMW_GEN_G_DrawCarsReflections 0x00903324u  /* bool */
#define NFSMW_GEN_G_DrawHUD 0x0057CAA8u  /* bool */
#define NFSMW_GEN_G_DrawLightFlares 0x008F2918u  /* bool */
#define NFSMW_GEN_G_ForceCarLOD 0x00903384u  /* CARPART_LOD */
#define NFSMW_GEN_G_ForceTireLOD 0x00903388u  /* CARPART_LOD */
#define NFSMW_GEN_G_IsFadeScreenOn 0x0091CAE4u  /* bool */
#define NFSMW_GEN_G_IsInNIS 0x0091606Cu  /* bool */
#define NFSMW_GEN_G_NOSFOVWidening 0x0091112Cu  /* std::uint16_t */
#define NFSMW_GEN_G_PrecullerMode 0x008FAE44u  /* ePrecullerMode */
#define NFSMW_GEN_G_SkipFE 0x00926064u  /* bool */
#define NFSMW_GEN_G_SkipFEDisableCops 0x008F86C0u  /* bool */
#define NFSMW_GEN_G_SkipFEDisableTraffic 0x00926094u  /* bool */
#define NFSMW_GEN_G_SkipFEPOVType 0x008F86C4u  /* ePlayerSettingsCameras */
#define NFSMW_GEN_G_SkipFEPlayerCar 0x008F86A8u  /* const char* */
#define NFSMW_GEN_G_SkipFETrafficDensity 0x00926090u  /* float */
#define NFSMW_GEN_G_StopUpdatingCamera 0x00911020u  /* bool */
#define NFSMW_GEN_G_TheGameFlowManager 0x00925E90u  /* GameFlowState */
#define NFSMW_GEN_G_TheOneCopManager 0x0090D5F4u  /* AICopManager* */
#define NFSMW_GEN_G_Tweak_GameBreakerCollisionMass 0x00901AECu  /* float */
#define NFSMW_GEN_G_Tweak_GameSpeed 0x00901B1Cu  /* float */
#define NFSMW_GEN_G_Tweak_InfiniteNOS 0x00937804u  /* bool */
#define NFSMW_GEN_G_Tweak_InfiniteRaceBreaker 0x00988E1Cu  /* bool */
#define NFSMW_GEN_G_Tweak_PauseCameraLock 0x0092584Cu  /* bool */
#define NFSMW_GEN_G_WindowHasLostFocus 0x00982C50u  /* bool */

/* ---- functions (126 unique of 153) ---- */
#define NFSMW_GEN_F_AIParams__AddTypeName 0x006685D0u  /* void __cdecl (AIParams*) */
#define NFSMW_GEN_F_AIPursuit__Construct 0x00443270u  /* Sim::IActivity* __cdecl (AIParams, UCrc32) */
#define NFSMW_GEN_F_AITarget__Acquire 0x00423860u  /* void __thiscall (AITarget*, ISimable*) */
#define NFSMW_GEN_F_AITarget__Clear 0x00409E60u  /* void __thiscall (AITarget*) */
#define NFSMW_GEN_F_AITarget__Construct 0x00418000u  /* void __thiscall (AITarget*, ISimable*) */
#define NFSMW_GEN_F_AITarget__Register 0x00423750u  /* void __thiscall (AITarget*, ISimable*) */
#define NFSMW_GEN_F_AITarget__TrackInternal 0x004180F0u  /* void __thiscall (AITarget*) */
#define NFSMW_GEN_F_AIVehicleCast_t__GetPlayerInstance 0x00891A80u  /* void  () */
#define NFSMW_GEN_F_AIVehicle__SetGoal 0x00422480u  /* void __thiscall (AIVehicle*, const UCrc32&) */
#define NFSMW_GEN_F_AbandonRace 0x0060DEB0u  /* void __cdecl () */
#define NFSMW_GEN_F_AwardPlayerBounty 0x00612220u  /* void __cdecl (std::int32_t) */
#define NFSMW_GEN_F_BeginGameFlowUnloadTrack 0x00667340u  /* void __cdecl () */
#define NFSMW_GEN_F_BlowEngine 0x0060AB30u  /* void __cdecl (ISimable*) */
#define NFSMW_GEN_F_Class__GetCollection 0x00455960u  /* Collection* __thiscall (Class*, std::uint32_t) */
#define NFSMW_GEN_F_Class__GetDefinition 0x00457380u  /* Definition* __thiscall (Class*, std::uint32_t) */
#define NFSMW_GEN_F_Class__GetFirstCollection 0x00456B00u  /* std::uint32_t __thiscall (Class*) */
#define NFSMW_GEN_F_Class__GetFirstDefinition 0x00451670u  /* std::uint32_t __thiscall (Class*) */
#define NFSMW_GEN_F_Class__GetNextCollection 0x00456B20u  /* std::uint32_t __thiscall (Class*, std::uint32_t) */
#define NFSMW_GEN_F_Class__GetNextDefinition 0x004573C0u  /* std::uint32_t __thiscall (Class*, std::uint32_t) */
#define NFSMW_GEN_F_Class__GetNumCollections 0x00453FC0u  /* std::uint32_t __thiscall (Class*) */
#define NFSMW_GEN_F_Class__GetNumDefinitions 0x00451660u  /* std::uint32_t __thiscall (Class*) */
#define NFSMW_GEN_F_ClearAIControl 0x00612420u  /* void __cdecl (bool) */
#define NFSMW_GEN_F_Collection__GetData 0x00454190u  /* T* __thiscall (Collection*, std::uint32_t, std::int32_t) */
#define NFSMW_GEN_F_Database__GetClass 0x00455BC0u  /* Class* __thiscall (Database*, std::uint32_t) */
#define NFSMW_GEN_F_DebugVehicleSelection__ChangePlayerVehicle 0x009B08F8u  /* void  () */
#define NFSMW_GEN_F_DisengageGPS 0x0041ACE0u  /* void __cdecl () */
#define NFSMW_GEN_F_EngageGPS 0x0042C830u  /* void __cdecl (UMath::Vector3*, float) */
#define NFSMW_GEN_F_FECarRecord__GetCost 0x00581730u  /* std::int32_t __thiscall (FECarRecord*) */
#define NFSMW_GEN_F_FECarRecord__GetManufacturerName 0x00581790u  /* const char* __thiscall (FECarRecord*) */
#define NFSMW_GEN_F_FECarRecord__GetType 0x005816B0u  /* CarType __thiscall (FECarRecord*) */
#define NFSMW_GEN_F_FECustomizationRecord__WriteRideIntoRecord 0x0056F2F0u  /* void __thiscall (FECustomizationRecord*, const RideInfo*) */
#define NFSMW_GEN_F_FECustomizationRecord__ctor 0x00581C20u  /* FECustomizationRecord* __thiscall (FECustomizationRecord*) */
#define NFSMW_GEN_F_FEObject__GetCenter 0x00524EE0u  /* void __cdecl (FEObject*, float*, float*) */
#define NFSMW_GEN_F_FEObject__GetObject 0x00524850u  /* FEObject* __cdecl (const char*, std::uint32_t) */
#define NFSMW_GEN_F_FEObject__GetSize 0x00515520u  /* void __cdecl (FEObject*, float*, float*) */
#define NFSMW_GEN_F_FEObject__SetCenter 0x00525050u  /* void __cdecl (FEObject*, float, float) */
#define NFSMW_GEN_F_FEObject__SetRotationZ 0x00514E20u  /* void __cdecl (FEObject*, float) */
#define NFSMW_GEN_F_FEObject__SetSize 0x005155E0u  /* void __cdecl (FEObject*, float, float) */
#define NFSMW_GEN_F_FEObject__SetVisible 0x00514C70u  /* void  () */
#define NFSMW_GEN_F_FEPlayerCarDB__AwardBonusCars 0x0056F0C0u  /* void __thiscall (FEPlayerCarDB*) */
#define NFSMW_GEN_F_FEPlayerCarDB__AwardRivalCar 0x005A41E0u  /* void __thiscall (FEPlayerCarDB*, Attrib::StringKey) */
#define NFSMW_GEN_F_FEPlayerCarDB__GetCarByIndex 0x0056ECF0u  /* FECarRecord* __thiscall (FEPlayerCarDB*, std::uint32_t) */
#define NFSMW_GEN_F_FEPlayerCarDB__GetCarRecordByHandle 0x0056ECC0u  /* FECarRecord* __thiscall (FEPlayerCarDB*, std::uint32_t) */
#define NFSMW_GEN_F_FEPlayerCarDB__GetCareerRecordByHandle 0x0056F120u  /* FECareerRecord* __thiscall (FEPlayerCarDB*, std::uint8_t) */
#define NFSMW_GEN_F_FEPlayerCarDB__GetNumCareerCars 0x005810E0u  /* std::size_t __thiscall (FEPlayerCarDB*) */
#define NFSMW_GEN_F_FEPlayerCarDB__GetNumCars 0x005812C0u  /* std::size_t __thiscall (FEPlayerCarDB*) */
#define NFSMW_GEN_F_FindCollection 0x00455FD0u  /* Collection* __cdecl (std::uint32_t, std::uint32_t) */
#define NFSMW_GEN_F_ForceAIControl 0x006123B0u  /* void __cdecl (bool) */
#define NFSMW_GEN_F_ForcePursuitBail 0x0062ACE0u  /* void __cdecl () */
#define NFSMW_GEN_F_ForcePursuitStart 0x0060AAC0u  /* void __cdecl () */
#define NFSMW_GEN_F_GIcon__CreateGeometry 0x005DE690u  /* WorldModel* __thiscall (GIcon*, std::uint32_t) */
#define NFSMW_GEN_F_GIcon__FindSection 0x005DE590u  /* std::uint32_t __thiscall (GIcon*) */
#define NFSMW_GEN_F_GIcon__SetPosition 0x005E5A90u  /* void __thiscall (GIcon*) */
#define NFSMW_GEN_F_GIcon__SnapToGround 0x005EA0F0u  /* void __thiscall (GIcon*) */
#define NFSMW_GEN_F_GIcon__Spawn 0x005EC270u  /* void __thiscall (GIcon*) */
#define NFSMW_GEN_F_GIcon__Unspawn 0x005E5A00u  /* void __thiscall (GIcon*) */
#define NFSMW_GEN_F_GIcon__ctor 0x005E5970u  /* void __thiscall (GIcon*, Type, const UMath::Vector3&, float) */
#define NFSMW_GEN_F_GIcon__dtor 0x005EBED0u  /* void __thiscall (GIcon*, bool) */
#define NFSMW_GEN_F_GManager__SpawnAllLoadedSectionIcons 0x005EDE20u  /* void __thiscall (GManager*) */
#define NFSMW_GEN_F_GManager__UnspawnAllIcons 0x005EA010u  /* void __thiscall (GManager*) */
#define NFSMW_GEN_F_GRaceStatus__DisableBarriers 0x005DBF00u  /* void __cdecl () */
#define NFSMW_GEN_F_GRuntimeInstance__GetDirection 0x005DACF0u  /* bool __thiscall (GRuntimeInstance*, UMath::Vector3&) */
#define NFSMW_GEN_F_GRuntimeInstance__GetPosition 0x005E2970u  /* bool __thiscall (GRuntimeInstance*, UMath::Vector3&) */
#define NFSMW_GEN_F_IAIHelicopter__GetIHandle 0x00404060u  /* IHandle* __cdecl () */
#define NFSMW_GEN_F_IAttachable__GetIHandle 0x00402820u  /* IHandle* __cdecl () */
#define NFSMW_GEN_F_ICause__GetIHandle 0x00405020u  /* IHandle* __cdecl () */
#define NFSMW_GEN_F_ICheater__GetIHandle 0x00405240u  /* IHandle* __cdecl () */
#define NFSMW_GEN_F_ICollisionBody__GetIHandle 0x004039C0u  /* IHandle* __cdecl () */
#define NFSMW_GEN_F_IDamageableVehicle__GetIHandle 0x00620FD0u  /* IHandle* __cdecl () */
#define NFSMW_GEN_F_IDamageable__GetIHandle 0x00405000u  /* IHandle* __cdecl () */
#define NFSMW_GEN_F_IEngine__GetIHandle 0x00404020u  /* IHandle* __cdecl () */
#define NFSMW_GEN_F_IGenericMessage__GetIHandle 0x005650B0u  /* IHandle* __cdecl () */
#define NFSMW_GEN_F_IHumanAI__GetIHandle 0x00403770u  /* IHandle* __cdecl () */
#define NFSMW_GEN_F_IPerpetrator__GetIHandle 0x004037E0u  /* IHandle* __cdecl () */
#define NFSMW_GEN_F_IPlayer__GetIHandle 0x006200D0u  /* IHandle* __cdecl () */
#define NFSMW_GEN_F_IPursuitAI__GetIHandle 0x004038E0u  /* IHandle* __cdecl () */
#define NFSMW_GEN_F_IPursuit__GetIHandle 0x004038C0u  /* IHandle* __cdecl () */
#define NFSMW_GEN_F_IRBVehicle__GetIHandle 0x004039E0u  /* IHandle* __cdecl () */
#define NFSMW_GEN_F_IRacer__GetIHandle 0x00403850u  /* IHandle* __cdecl () */
#define NFSMW_GEN_F_ISimpleChopper__GetIHandle 0x00404050u  /* IHandle* __cdecl () */
#define NFSMW_GEN_F_ISpikeable__GetIHandle 0x0068CC70u  /* IHandle* __cdecl () */
#define NFSMW_GEN_F_ISuspension__GetIHandle 0x00404040u  /* IHandle* __cdecl () */
#define NFSMW_GEN_F_ITrafficAI__GetIHandle 0x00403950u  /* IHandle* __cdecl () */
#define NFSMW_GEN_F_ITransmission__GetIHandle 0x00404010u  /* IHandle* __cdecl () */
#define NFSMW_GEN_F_IVehicleAI__GetIHandle 0x00403700u  /* IHandle* __cdecl () */
#define NFSMW_GEN_F_IVehicle__GetIHandle 0x004040E0u  /* IHandle* __cdecl () */
#define NFSMW_GEN_F_JumpToCarLot 0x00605250u  /* void __cdecl () */
#define NFSMW_GEN_F_JumpToSafehouse 0x006052B0u  /* void __cdecl () */
#define NFSMW_GEN_F_Matrix4__ToQuaternion 0x005D06A0u  /* void __cdecl (const Matrix4*, Vector4*) */
#define NFSMW_GEN_F_NavigatePlayerTo 0x00605360u  /* void __cdecl (GRuntimeInstance*, GTrigger*, float, bool) */
#define NFSMW_GEN_F_Package__CanInstallJunkman 0x00677FE0u  /* bool __cdecl (const Attrib::Gen::pvehicle&, Type) */
#define NFSMW_GEN_F_Package__GetPercent 0x00677F80u  /* float __cdecl (const Attrib::Gen::pvehicle&, Type) */
#define NFSMW_GEN_F_Package__RemoveJunkman 0x0067C220u  /* void __cdecl (const Attrib::Gen::pvehicle&, Type) */
#define NFSMW_GEN_F_Package__RemovePart 0x00678530u  /* void __cdecl (const Attrib::Gen::pvehicle&, Type) */
#define NFSMW_GEN_F_Package__SetJunkman 0x00678150u  /* void __cdecl (const Attrib::Gen::pvehicle&, Type) */
#define NFSMW_GEN_F_Package__SetLevel 0x00678AD0u  /* void __cdecl (const Attrib::Gen::pvehicle&, Type) */
#define NFSMW_GEN_F_Package__SetMaximum 0x0067F950u  /* void __cdecl (Attrib::Gen::pvehicle&) */
#define NFSMW_GEN_F_ResetCar__Construct 0x00689820u  /* IResetable* __cdecl (BehaviorParams) */
#define NFSMW_GEN_F_RideInfo__GetPart 0x00739C70u  /* CarPart* __thiscall (RideInfo*, CarSlotId) */
#define NFSMW_GEN_F_RideInfo__SetRandomPaint 0x00759800u  /* void __thiscall (RideInfo*) */
#define NFSMW_GEN_F_RideInfo__SetRandomPart 0x007596E0u  /* void __thiscall (RideInfo*, CarSlotId, eCareerUpgradeLevels) */
#define NFSMW_GEN_F_RideInfo__SetRandomParts 0x0075B220u  /* void __thiscall (RideInfo*) */
#define NFSMW_GEN_F_RideInfo__SetStockParts 0x007594A0u  /* void __thiscall (RideInfo*) */
#define NFSMW_GEN_F_RideInfo__SetUpgradePart 0x00759470u  /* void __thiscall (RideInfo*, CarSlotId, eCareerUpgradeLevels) */
#define NFSMW_GEN_F_SabotageEngine 0x0060AB60u  /* void __cdecl (ISimable*, float) */
#define NFSMW_GEN_F_SetCopsEnabled 0x00604F40u  /* void __cdecl (bool) */
#define NFSMW_GEN_F_SetWorldHeat 0x00612660u  /* void __cdecl (float) */
#define NFSMW_GEN_F_ShakeCamera 0x0062B110u  /* void __cdecl () */
#define NFSMW_GEN_F_ShowPauseMenu 0x006050F0u  /* void __cdecl () */
#define NFSMW_GEN_F_SmackableParams__AddTypeName 0x00620FF0u  /* void __cdecl (SmackableParams*) */
#define NFSMW_GEN_F_Smackable__Construct 0x006895A0u  /* ISimable* __cdecl (SmackableParams, UCrc32) */
#define NFSMW_GEN_F_StringToKey 0x00454640u  /* std::uint32_t __cdecl (const char*) */
#define NFSMW_GEN_F_TimeOfDay__GetInstance 0x009B392Cu  /* void  () */
#define NFSMW_GEN_F_ValidatePlayer_t__GetPlayerInstance 0x008B0B10u  /* void  () */
#define NFSMW_GEN_F_Vector4__ExtractXAxis 0x005CA6F0u  /* void __cdecl (const Vector4*, Vector3*) */
#define NFSMW_GEN_F_Vector4__ExtractYAxis 0x005CA7B0u  /* void __cdecl (const Vector4*, Vector3*) */
#define NFSMW_GEN_F_Vector4__ExtractZAxis 0x005CA870u  /* void __cdecl (const Vector4*, Vector3*) */
#define NFSMW_GEN_F_Vector4__ToMatrix4 0x005CA910u  /* void __cdecl (const Vector4*, Matrix4*) */
#define NFSMW_GEN_F_VehicleParams__AddTypeName 0x004040F0u  /* void __cdecl (VehicleParams*) */
#define NFSMW_GEN_F_Volatile__RemoveStatus 0x009384B0u  /* void  () */
#define NFSMW_GEN_F_Volatile__RemoveStatusPrev 0x009383B0u  /* void  () */
#define NFSMW_GEN_F__IList__Find 0x005D59F0u  /* T* __thiscall (_IList*, IHandle*) */
#define NFSMW_GEN_F_bStringHash 0x00460BF0u  /* std::uint32_t __cdecl (const char*) */
#define NFSMW_GEN_F_cFrontEndDatabase__GetPlayerSettings 0x0091CF90u  /* void  () */
#define NFSMW_GEN_F_pvehicle__TryGetInstance 0x004E4EA0u  /* pvehicle* __thiscall (pvehicle&, std::uint32_t, bool, bool) */
#define NFSMW_GEN_F_stringhash32 0x005CC240u  /* std::uint32_t __cdecl (const char*) */

#endif
