#!/usr/bin/env python3
"""
codegen.py — regenerate nfsmw_sdk headers from the JSON knowledge base.

Source of truth: the vendored copies in sdk/data/ (the SDK repo is
standalone, so CI can verify the generated headers). A maintainer
updating the RE database must re-sync sdk/data/ from the main repo's
docs/ (cp docs/*.json sdk/data/) and re-run this tool. If sdk/data/ is
absent, falls back to ../../docs/ for in-place main-repo regeneration.

Reads (sdk/data/ first, then ../../docs/ fallback):
  sdk_addrs.json                (181 records: 153 fn + 28 globals)
  attribute_cracks_verified.json (294 {hash: name} verified attrs)
  sdk_enums.json                 (65 enums w/ members)

Writes (address tables only; hand-written helper code is preserved):
  ../include/nfsmw_sdk/_generated_addrs.h
  ../include/nfsmw_sdk/_generated_enums.h
  ../include/nfsmw_sdk/_generated_attrs.h

globals.h / functions.h / enums.h / attributes.h #include the generated
files for raw constants and layer typed accessors on top. Re-running codegen
never clobbers hand-written helper code.

Usage:
  python3 tools/codegen.py            # regenerate
  python3 tools/codegen.py --check    # exit 1 if out of date (CI guard)
"""

import json
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
SDK = os.path.dirname(HERE)
REPO = os.path.dirname(SDK)
DATA = os.path.join(SDK, "data")          # vendored — SDK repo source of truth
DOCS = os.path.join(REPO, "docs")         # main-repo fallback for maintainers
INC = os.path.join(SDK, "include", "nfsmw_sdk")


def load_json(name):
    for root in (DATA, DOCS):
        path = os.path.join(root, name)
        if os.path.exists(path):
            with open(path) as f:
                return json.load(f)
    print(f"  (skip: {name} not found in sdk/data/ or ../../docs/)",
          file=sys.stderr)
    return None


def ident(s):
    out = "".join(c if c.isalnum() else "_" for c in str(s))
    if out and out[0].isdigit():
        out = "_" + out
    return out


def fmt_addr(v):
    if isinstance(v, str):
        v = int(v, 16) if v.lower().startswith("0x") else int(v)
    return f"0x{v:08X}u"


def gen_addrs():
    recs = load_json("sdk_addrs.json") or []
    out = [
        "/* AUTO-GENERATED by tools/codegen.py — DO NOT EDIT.",
        " * Source: docs/sdk_addrs.json */",
        "#ifndef NFSMW_SDK_GENERATED_ADDRS_H",
        "#define NFSMW_SDK_GENERATED_ADDRS_H",
        "",
    ]
    fns = [r for r in recs if r.get("kind") == "function"]
    gls = [r for r in recs if r.get("kind") == "global"]

    out.append(f"/* ---- globals ({len(gls)}) ---- */")
    for r in sorted(gls, key=lambda r: r.get("name") or ""):
        nm = r.get("name") or r.get("fullname")
        if not nm:
            continue
        ty = r.get("type", "?")
        out.append(f"#define NFSMW_GEN_G_{ident(nm)} {fmt_addr(r['addr'])}  /* {ty} */")
    out.append("")

    # Dedup by fullname: some records repeat a name with a stub
    # "None None (None)" signature. Prefer the record with real metadata.
    def richness(r):
        return sum(1 for k in ("ret", "cc", "args") if r.get(k) not in (None, "", "None"))

    by_name = {}
    for r in fns:
        full = r.get("fullname") or r.get("method")
        if not full:
            continue
        key = ident(full)
        if key not in by_name or richness(r) > richness(by_name[key]):
            by_name[key] = r

    out.append(f"/* ---- functions ({len(by_name)} unique of {len(fns)}) ---- */")
    for key in sorted(by_name):
        r = by_name[key]
        cc = r.get("cc") or ""
        ret = r.get("ret") or "void"
        args = r.get("args") or ""
        out.append(
            f"#define NFSMW_GEN_F_{key} {fmt_addr(r['addr'])}"
            f"  /* {ret} {cc} ({args}) */"
        )
    out.append("")
    out.append("#endif")
    return "\n".join(out) + "\n"


def gen_attrs():
    d = load_json("attribute_cracks_verified.json") or {}
    out = [
        "/* AUTO-GENERATED by tools/codegen.py — DO NOT EDIT.",
        " * Source: docs/attribute_cracks_verified.json */",
        "#ifndef NFSMW_SDK_GENERATED_ATTRS_H",
        "#define NFSMW_SDK_GENERATED_ATTRS_H",
        "",
        f"/* ---- verified attribute name hashes ({len(d)}) ---- */",
    ]
    for h, nm in sorted(d.items(), key=lambda kv: kv[1]):
        out.append(f"#define NFSMW_ATTR_{ident(nm)} {fmt_addr(h)}")
    out.append("")
    out.append("#endif")
    return "\n".join(out) + "\n"


import re

_LIMITS = {
    "UINT8_MAX": "0xFFu", "UINT16_MAX": "0xFFFFu",
    "UINT32_MAX": "0xFFFFFFFFu", "UINT64_MAX": "0xFFFFFFFFFFFFFFFFull",
    "INT8_MAX": "0x7F", "INT16_MAX": "0x7FFF", "INT32_MAX": "0x7FFFFFFF",
}


def sanitize_expr(expr, enum_ident, member_idents):
    """Turn an NFSPluginSDK C++ enum initializer into portable C."""
    s = str(expr)
    # strip C++ functional casts: static_cast<...>(X) -> (X)
    s = re.sub(r"static_cast<[^>]+>\s*\(", "(", s)
    # strip C-style casts: (std::uint32_t)X / (uint8_t)X -> X
    s = re.sub(r"\(\s*(?:std::)?u?int(?:8|16|32|64)_t\s*\)", "", s)
    s = s.replace("std::uint32_t", "").replace("std::uint8_t", "")
    for k, v in _LIMITS.items():
        s = re.sub(rf"\b{k}\b", v, s)
    # prefix bare sibling-member references with NFSMW_<enum>_

    def repl(mt):
        tok = mt.group(0)
        if tok in member_idents:
            return f"NFSMW_{enum_ident}_{tok}"
        return tok

    s = re.sub(r"[A-Za-z_]\w*", repl, s)
    return s.strip()


def gen_enums():
    enums = load_json("sdk_enums.json") or []
    out = [
        "/* AUTO-GENERATED by tools/codegen.py — DO NOT EDIT.",
        " * Source: docs/sdk_enums.json */",
        "#ifndef NFSMW_SDK_GENERATED_ENUMS_H",
        "#define NFSMW_SDK_GENERATED_ENUMS_H",
        "",
        "#include <stdint.h>",
        "",
    ]
    seen = {}
    for e in sorted(enums, key=lambda e: (e.get("name") or "", e.get("header") or "")):
        nm = e.get("name")
        if not nm:
            continue
        en = ident(nm)
        # Multiple distinct NFSPluginSDK enums (often class-nested) share a
        # leaf name; qualify duplicates with the header stem to keep C names
        # unique. First occurrence keeps the bare name.
        if en in seen:
            stem = os.path.splitext(os.path.basename(e.get("header") or ""))[0]
            cand = f"{en}_{ident(stem)}" if stem else f"{en}_{seen[en]}"
            while cand in seen:
                seen[en] += 1
                cand = f"{en}_{seen[en]}"
            en = cand
        seen[en] = seen.get(en, 0) + 1
        member_idents = {ident(m.get("name")) for m in e.get("members", []) if m.get("name")}
        out.append(f"typedef enum NFSMW_{en} {{")
        auto = 0
        for m in e.get("members", []):
            mn = ident(m.get("name"))
            expr = m.get("expr")
            if expr is not None and str(expr) != "":
                val = sanitize_expr(expr, en, member_idents)
                out.append(f"    NFSMW_{en}_{mn} = {val},")
            else:
                out.append(f"    NFSMW_{en}_{mn} = {auto},")
                auto += 1
        out.append(f"}} NFSMW_{en};")
        out.append("")
    out.append("#endif")
    return "\n".join(out) + "\n"


TARGETS = {
    "_generated_addrs.h": gen_addrs,
    "_generated_attrs.h": gen_attrs,
    "_generated_enums.h": gen_enums,
}


def main():
    check = "--check" in sys.argv
    os.makedirs(INC, exist_ok=True)
    stale = False
    for fname, fn in TARGETS.items():
        content = fn()
        path = os.path.join(INC, fname)
        if check:
            cur = open(path).read() if os.path.exists(path) else None
            if cur != content:
                print(f"{fname} out of date — run codegen.py", file=sys.stderr)
                stale = True
            else:
                print(f"{fname} up to date")
        else:
            with open(path, "w") as f:
                f.write(content)
            print(f"wrote {fname} ({content.count(chr(10))} lines)")
    if check and stale:
        sys.exit(1)


if __name__ == "__main__":
    main()
